### PR TITLE
Add awoodson13-lamesa list

### PR DESCRIPTION
**Pull request by awoodson13**
list of restaurants

### CODE REVIEW

**Comment by githubteacher** [comment]
@awoodson13 I really like 🌯 , where should I go to get one the size of my arm? 💪

**Comment by mbmccollum** [comment]
Are there any good seafood places love great seafood

**Comment by mbmccollum** [comment]
Fish and shrimp are my fvorites

**Comment by awoodson13** [comment]
added cortijas

**Pull request merged**
